name: Latex-Build-Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-latex:
    # Name the Job
    name: Compile LaTeX
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs the Super-Linter action
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Trefois_CV.tex
        env:
          DEFAULT_BRANCH: main

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Trefois_CV.pdf
          draft: false
          prerelease: false